debug:
	@echo ============================
	@echo start make mkswf debug config
	@echo ============================
	ndk-build
release:
	@echo ============================
	@echo start make mkswf release config
	@echo ============================
	ndk-build -B NDK_DEBUG=0
default:
	@echo ============================
	@echo start make mkswf default config
	@echo ============================
	ndk-build
clean:
	@echo =====================================
	@echo start make mkswf clean
	@echo =====================================
	ndk-build clean